services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/main
    depends_on:
      - db
volumes:
  postgres-data:
